# Site settings
title: Building Regulation Notes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Drawings 30 years ago were drawings anotated with brief notes to describe
  the necessary elements of construction. With the increase in the number of
  building regulations over the years the number of notes has substantially 
  increased. Very often these are scattered all over the drawings to the point
  that in many cases they are often contrdictory and disorganised. This site 
  seeks to solve this problem by providing an organised set of notes that can 
  be used to provide information to assist in compliance with the Building Regulations.
baseurl: "/mynotessite" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
collections:
  regnotes:
    output: true
    permalink: /regulationnotes/:path/
  regsections:
    output: true
    permalink: /regulationsections/:path/
    